# Generated by Django 4.1.2 on 2023-01-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('farmer_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=9)),
                ('father_or_husband_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=12)),
                ('whatsapp_number', models.CharField(max_length=12)),
                ('local_or_outsider', models.CharField(blank=True, max_length=9, null=True)),
                ('organic_farming', models.BooleanField(blank=True, null=True)),
                ('single_seeding', models.BooleanField(blank=True, null=True)),
                ('alternative_cropping', models.BooleanField(blank=True, null=True)),
                ('seed_vareity_advice', models.BooleanField(blank=True, null=True)),
                ('lease_own_land', models.BooleanField(blank=True, null=True)),
                ('farm_rented_land', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
