# Generated by Django 4.1.2 on 2023-01-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_farmer_created_at_farmer_is_admin_farmer_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
